theme: jekyll-theme-architect
title: ClancyCoin
description: A (Joke) Fork of Bitcoin Core
show_downloads: true
collections:
        authors:
                output: true

defaults:
        - scope:
                path: ""
                type: "authors"
                values:
                layout: "author"
        - scope:
                path: ""
                type: "posts"
                values:
                layout: "post"
        - scope:
                path: ""
                values:
                layout: "default"
