.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. clancycoin_qt test_clancycoin_qt
clean: FORCE
	$(MAKE) -C .. clancycoin_qt_clean test_clancycoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_clancycoin_qt_check
clancycoin-qt clancycoin-qt.exe: FORCE
	 $(MAKE) -C .. clancycoin_qt
